name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install ninja-build
        sudo pip3 install meson

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Sass globally
      run: npm install -g sass

    - name: Update version
      id: update_version
      run: |
        VERSION=$(cat version)
        MAJOR=$(echo $VERSION | cut -d'.' -f1)
        MINOR=$(echo $VERSION | cut -d'.' -f2)
        if (( MINOR >= 10 )); then
          MAJOR=$((MAJOR + 1))
          MINOR=0
        else
          MINOR=$((MINOR + 1))
        fi
        echo "$MAJOR.$MINOR" > version
        echo "version=$MAJOR.$MINOR" >> $GITHUB_ENV

    - name: Build theme
      run: |
        meson setup -Dprefix="/home/runner/work/${{ github.repository }}/build" build
        ninja -C build install
        cd /home/runner/work/${{ github.repository }}/build/share/themes
        tar -cJf ${{ github.event.repository.name }}.tar.xz ${{ github.event.repository.name }} ${{ github.event.repository.name }}-dark
        mv /home/runner/work/${{ github.repository }}/build/share/themes/${{ github.event.repository.name }}.tar.xz /home/runner/work/${{ github.repository }}/build/share/themes/${{ github.event.repository.name }}v${{ env.version }}.tar.xz

    - name: Get previous release version
      id: prev_release
      run: |
        PREV_VERSION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/releases/latest \
        | jq -r '.tag_name')
        echo "prev_version=$PREV_VERSION" >> $GITHUB_ENV

    - name: Create and Upload Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        name: ${{ github.event.repository.name }} v${{ env.version }}
        body: >
          Full Changelog: https://github.com/${{ github.repository }}/compare/${{ env.prev_version }}...v${{ env.version }}
        draft: false
        prerelease: false
        files: |
          /home/runner/work/${{ github.repository }}/build/share/themes/${{ github.event.repository.name }}v${{ env.version }}.tar.xz

    - name: Commit and push
      run: |
        git config user.name "GitHub-Actions"
        git config user.email "<>"
        git add version
        git commit -m "Bump version to ${{ env.version }}"
        git push
